### ISSUE TITLE
error on download page on your site

### ISSUE THREAD

**Issue by Alexandre17220** [Myddleware/myddleware#45] opened 2017-08-22 10:18 UTC
Hi, 
Just for information, if you want to download midlleware :
"
![image](https://user-images.githubusercontent.com/7665521/29560926-e682e3be-8733-11e7-9d7c-070cd2c2aae9.png)
"
Thanks,

**Comment by Myddleware** [comment] 2017-08-22 11:51
Thanks so much for telling us Alexander.
The problem is now fixed.
Have a nice day.

**Closed as completed by Myddleware** 2017-08-22 11:51 UTC
