### ISSUE TITLE
Myd3.15 pagination issue

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#800] opened 2022-08-04 08:33 UTC
Hi,
in document list, if I switch page I get 404 error.
CAn you reproduce this issue?
example url:
http://mymyddleware/index.php/rule/flux/list/page-7

**Comment by Myddleware** [comment] 2022-08-10 22:13
You are right, we have an issue with pagination in Myddleware 3. We will fix it.
If you want to see more result right now, here is a wrokaround. You can change the config in table config. You can set 10 000 here : 
![image](https://user-images.githubusercontent.com/11330301/184029524-cbe14cf4-acb3-41ef-a4eb-c3a3b8a9fc6f.png)

So you will have only one page with a lot of result;

I 'll let you know once the issue is solved.

**Comment by Myddleware** [comment] 2022-08-10 22:14
@AlexMyddleware , could you have a look into this issue please ? 
Thanks.

**Comment by AlexMyddleware** [comment] 2022-08-11 06:37
@Myddleware I will look into it right away.

**Comment by AlexMyddleware** [comment] 2022-08-11 12:38
Hello @simonetravaglini , I found the bug and fixed it, the fix will be present in myddleware 3.1.8. 
You can also correct it manually right away by removing 2 lines of your \src\Controller\FluxController.php.

They are respectively these lines:
`if ($form->get('click_filter')->isClicked()) {`
line 306
and the closing curling bracket
` } // end clicked`
line 377

You can check out [this commit](https://github.com/Myddleware/myddleware/commit/5243427d2c7273f6cdc0c9feb58764361470f6b3) i made.

If you need any additional help for this, please let me know.

**Closed as completed by AlexMyddleware** 2022-08-11 12:38 UTC
Labels: bug, Myddleware 3.0
